"""AtlasRow — the per-model record + ``emit_row`` (spec 002 §7, tasks 3 & 5).

A model that passes the contract (``contract.ContractModel`` + CI gates) emits one
row. The row columns are spec 002 §7:

    model_family, mechanism_label, contract_status, sf_profile,
    intervention_response_signature, claim_admissibility_profile, audit_profile,
    replication_stability, failure_transparency_note

This makes spec 002 §4's three tasks identical: a model entering
``packages/abm_models`` + a frozen semantic label ⇒ an Atlas row, generated by
*dogfooding* the contract (not a separate infra project).

Honesty rules (spec 002 §11): the intervention-response column is ``None`` with a
reason for every C0 model (no exposed channel yet); price-less models get a
structured ``battery_non_applicable`` failure note rather than a faked SF profile.
"""

from __future__ import annotations

import numpy as np
from abm_models import returns_of
from stylized_facts import stylized_facts_summary

from . import profiles as P
from .contract import ContractModel, check_determinism, detect_conformance
from .registry import FROZEN_REGISTRY, build_model


def _safe_returns(result: dict) -> np.ndarray | None:
    """Return-series extractor; None for price-less models (MG/GCMG)."""
    try:
        r = returns_of(result)
    except KeyError:
        return None
    r = np.asarray(r, dtype=np.float64)
    return r if r.size else None


def _replication_stability(name: str, seeds: tuple[int, ...]) -> tuple[P.ReplicationStability, bool]:
    """SF-summary CV across seeds. Returns (axis, returns_available)."""
    summaries = []
    returns_available = True
    for s in seeds:
        result = build_model(name).run(seed=s)
        r = _safe_returns(result)
        if r is None:
            returns_available = False
            break
        summaries.append(stylized_facts_summary(r))
    if not returns_available or not summaries:
        return (
            P.ReplicationStability(len(seeds), {}, 0.0, "price-less: return SF battery N/A"),
            False,
        )

    def _cv(values: list[float]) -> float:
        arr = np.asarray([v for v in values if np.isfinite(v)], dtype=np.float64)
        if arr.size < 2 or arr.mean() == 0:
            return float("nan")
        return float(arr.std() / abs(arr.mean()))

    metric_cv = {
        "std": _cv([s["std"] for s in summaries]),
        "hill_alpha": _cv([s["hill_alpha"] for s in summaries]),
        "kurt_w1": _cv([s["kurt"][1] for s in summaries]),
        "vol_acf_lag1": _cv([s["vol_acf"][1] for s in summaries]),
    }
    finite = [v for v in metric_cv.values() if np.isfinite(v)]
    # Lower CV → higher stability score; squash with 1/(1+mean_cv).
    score = 1.0 / (1.0 + float(np.mean(finite))) if finite else 0.0
    return P.ReplicationStability(len(seeds), metric_cv, score), True


def emit_row(name: str, *, seeds: tuple[int, ...] = (1, 2, 3, 4, 5)) -> dict:
    """Generate one Atlas row for a canonical model (spec 002 §7)."""
    if name not in FROZEN_REGISTRY:
        raise KeyError(f"{name} has no frozen semantic label")
    label = FROZEN_REGISTRY[name]

    # --- CI-gate-equivalent checks (spec 002 §6) ---
    determinism_ok = check_determinism(build_model(name), seed=seeds[0])
    cm = ContractModel(build_model(name), config=dict(label.atlas_config))
    cm.reset(seeds[0])
    prov = cm.emit_prov()
    prov_ok = all(prov.get(f) not in (None, "") for f in ("uuid", "seed", "output_sha256"))
    conformance = detect_conformance(cm, prov_ok=prov_ok, determinism_ok=determinism_ok)

    # --- SF profile (or structured failure for price-less models) ---
    result0 = cm.emit()
    r0 = _safe_returns(dict(result0))
    rep_axis, returns_available = _replication_stability(name, seeds)
    if returns_available and r0 is not None:
        sf_profile: dict | None = stylized_facts_summary(r0)
        failure = P.failure_transparency(
            has_failure=False, taxonomy=None, reproducible=True, contract_ok=True
        )
    else:
        sf_profile = None
        failure = P.failure_transparency(
            has_failure=True,
            taxonomy="battery_non_applicable",
            reproducible=determinism_ok,
            contract_ok=True,
        )

    # --- six-axis scoring profile (spec 002 §8) ---
    profile = P.ScoringProfile(
        claim_admissibility=P.claim_admissibility(prov["reach_claim"], ("reported",)),
        audit_completeness=P.audit_completeness(prov, determinism_verified=determinism_ok),
        intervention_coverage=P.intervention_coverage(n_exposed_channels=len(cm.channels)),
        mechanism_separability=P.mechanism_separability_pending(label.declared_channels),
        replication_stability=rep_axis,
        failure_transparency=failure,
    )

    return {
        "name": name,
        "model_family": label.family,
        "mechanism_label": label.mechanism_label,
        "reference": label.reference,
        "contract_status": conformance.name,  # "C0" | "C2"
        "declared_channels": list(label.declared_channels),
        "exposed_channels": list(cm.channels),
        "sf_profile": sf_profile,
        "intervention_response_signature": None,  # honest: requires C1 (Finding 0002)
        "intervention_response_status": "pending_c1",
        "claim_admissibility_profile": profile.claim_admissibility.to_dict(),
        "audit_profile": profile.audit_completeness.to_dict(),
        "replication_stability": profile.replication_stability.to_dict(),
        "failure_transparency_note": profile.failure_transparency.to_dict(),
        "scoring_profile": profile.to_dict(),
        "radar": profile.radar(),
        "provenance": prov,
        "diversity_tags": list(label.diversity_tags),
    }
